// Generated by CoffeeScript 1.10.0
(function() {
  var Airtable, base, getStdin;

  getStdin = require('get-stdin');

  Airtable = require('airtable');

  base = new Airtable({
    apiKey: 'keya5owBYIn0zRzxP'
  }).base('app2PLtM6KVLhzhrJ');

  getStdin().then(function(dataToUpdate) {
    return base('Bugs & Issues').update(dataToUpdate.record, {
      'Assigned to': dataToUpdate.assignTo
    }, function(err, record) {
      if (err) {
        console.error(err);
        return;
      }
      return console.log(record.get('Assigned to'));
    });
  });

}).call(this);
