// Generated by CoffeeScript 1.10.0
(function() {
  var FaaS, async, rp;

  rp = require('request-promise');

  async = require('async');

  FaaS = (function() {
    function FaaS(url) {
      this.options = {
        json: true,
        url: url,
        method: 'POST'
      };
      this.get = (function(_this) {
        return function(body) {
          _this.options.method = 'GET';
          _this.options.body = body;
          return rp(_this.options);
        };
      })(this);
      this.post = (function(_this) {
        return function(body) {
          _this.options.method = 'POST';
          _this.options.body = body;
          return rp(_this.options);
        };
      })(this);
    }

    return FaaS;

  })();

}).call(this);
