// Generated by CoffeeScript 1.10.0
(function() {
  var Chain, getStdin, submitToAirtable, updateGithubIssue;

  Chain = require('./faas-chain');

  getStdin = require('get-stdin');

  submitToAirtable = new Chain('http://45.63.7.154:8080/function/faas_submitentry');

  updateGithubIssue = new Chain('http://45.63.7.154:8080/faas_updategithubissue');

  getStdin().then(function(incomingPayload) {
    var airtableEntry;
    return airtableEntry = {
      'Issue': incomingPayload.issue.id,
      'Title': incomingPayload.issue.title,
      'Labels': incomingPayload.issue.labels[0].name,
      'Repo': incomingPayload.repository.full_name,
      'Priority': 'High',
      'Status': 'Backlog',
      'Bug Source': 'Github Issue',
      'Description': incomingPayload.issue.body,
      'Notified Users?': true
    };
  }).then(function(airtableEntry) {
    return submitToAirtable.post(airtableEntry);
  }).then(function(response) {
    return updateGithubIssue.post(response);
  }).then(console.log.bind(console));

}).call(this);
