// Generated by CoffeeScript 1.10.0
(function() {
  var Airtable, base, getStdin;

  getStdin = require('get-stdin');

  Airtable = require('airtable');

  base = new Airtable({
    apiKey: 'keya5owBYIn0zRzxP'
  }).base('app2PLtM6KVLhzhrJ');

  getStdin().then(function() {
    var done, page;
    return base('Team Members').select({
      maxRecords: 10,
      view: 'Main View'
    }).eachPage(page = function(records, fetchNextPage) {
      var compare, i, leastIssues, len, user;
      leastIssues = records[0];
      compare = function(user) {
        if (user.get('In-progress Issues') < leastIssues.get('In-progress Issues')) {
          return leastIssues = user;
        }
      };
      for (i = 0, len = records.length; i < len; i++) {
        user = records[i];
        compare(user);
      }
      console.log(JSON.stringify({
        id: leastIssues.id,
        githubUserName: leastIssues.get('GitHub User')
      }));
      return fetchNextPage();
    }, done = function(err) {
      if (err) {
        return console.err(err);
      }
    });
  })["catch"](console.log.bind(console));

}).call(this);
