// Generated by CoffeeScript 1.10.0
(function() {
  var Airtable, base, getStdin, payload;

  getStdin = require('get-stdin');

  Airtable = require('airtable');

  base = new Airtable({
    apiKey: 'keya5owBYIn0zRzxP'
  }).base('app2PLtM6KVLhzhrJ');

  payload = require('./payload.json');

  getStdin().then(function(entry) {
    base('Bugs & Issues').create(entry, function(err, record) {
      if (err) {
        console.log(err);
        return;
      }
      return console.log(record.getId());
    });
  })["catch"](console.log.bind(console));

}).call(this);
