// Generated by CoffeeScript 1.10.0
(function() {
  var Airtable, base, done, page;

  Airtable = require('airtable');

  base = new Airtable({
    apiKey: 'keya5owBYIn0zRzxP'
  }).base('app2PLtM6KVLhzhrJ');

  base('Team Members').select({
    view: 'Main View'
  }).eachPage(page = function(records, fetchNextPage) {
    records.forEach(function(record) {
      var user;
      user = {
        name: record.get('Name'),
        adminID: record.get('Admin ID'),
        tickets: record.get('# In-progress Issues')
      };
      return console.log('Retrieved', user);
    });
    return fetchNextPage();
  });

  done = function(err) {
    if (err) {
      return console.log(err);
    }
  };

}).call(this);
